services:
  # Backend API Service
  - type: web
    name: rcu-app-api
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: rcu-app-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_URL
        fromService:
          type: web
          name: rcu-app-frontend
          envVarKey: RENDER_EXTERNAL_URL
    healthCheckPath: /docs
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: rcu-app-frontend
    runtime: static
    region: oregon
    branch: main
    buildCommand: cd frontend/my-react-app && bash render-build.sh
    staticPublishPath: frontend/my-react-app/dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: rcu-app-api
          envVarKey: RENDER_EXTERNAL_URL
    autoDeploy: true

# Database
databases:
  - name: rcu-app-db
    databaseName: rcu_app
    user: rcu_app_user
    region: oregon
    plan: free
    ipAllowList: []

